name: 'mac'
on: ['workflow_dispatch']
jobs:
  fuckintosh:
    runs-on: 'macos-latest'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          repository: 'kuuote-sandbox/priv'
          token: ${{ secrets.PAT }}
      - name: 'Run script'
        run: './run'
