name: 'run'
on: ['workflow_dispatch']
jobs:
  yeah:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          repository: 'kuuote-sandbox/priv'
          token: ${{ secrets.PAT }}
      - name: 'Run script'
        run: './run'
