name: 'tmate'
on: ['workflow_dispatch']
jobs:
  mac:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          repository: 'kuuote-sandbox/priv'
          token: ${{ secrets.PAT }}
      - uses: 'mxschmitt/action-tmate@v3'
