name: 'ubuntu'
on: ['workflow_dispatch']
jobs:
  oobunchu:
    runs-on: 'ubuntu-latest'
    steps:
      - run: 'date > date'
      - uses: 'actions/cache@v4'
        with:
          path: ~/cache
          key: generic-cache-${{ hashFiles('date') }}
          restore-keys: generic-cache-
      - uses: 'actions/checkout@v2'
        with:
          repository: 'kuuote-sandbox/priv'
          token: ${{ secrets.PAT }}
      - name: 'Run script'
        run: './run'
