name: 'ubuntuarm'
on: ['workflow_dispatch']
jobs:
  oobunchu:
    runs-on: 'ubuntu-24.04-arm'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          repository: 'kuuote-sandbox/priv'
          token: ${{ secrets.PAT }}
      - name: 'Run script'
        run: './run'
